### ISSUE TITLE
问题咨询

### ISSUE THREAD

**Issue by keepindy** [qstesiro/Larva#4]
遇到以下几个疑惑，能否指点一下：
1，Breakpoint相关命令的写法
BreakpointManager.instance().append(breakpoint);  建议可以在if (null != location)里面才加，这样可以解决没找到匹配的断点 下次又不能执行相同断点的问题。

2，在android上使用，偶尔会出现设置了断点，也找到了匹配的断点，但相关线程未挂起、断点未生效的情况
有更好的方法可以避免吗？

3，在android上，偶尔会出现在前一个页面设置下一个页面的断点，比如方法断点、行断点，在MachineManager.instance().allClasses()中会找不到匹配的class，从而导致断点未设置成功

4，如何打印出类成员变量、方法参数的运行时具体赋值？特别是对象类型的参数 或者 对象类型的成员变量
例如：
1）public void updateData(List<TabListElement> tablist) { }

breakpoint.method "com.XXX.XXX.updateData(java.util.List)" {

template.list tablist; // 这里该怎么正确使用template 或者 print 来获取tablist中各个元素的取值呢？以及TabListElement内部的取值情况呢？
}

**Comment by qstesiro** [comment]
具体内容已经通过邮件回复，希望对你有帮助：）

**Comment by qstesiro** [comment]
修改了几个bug，请先更新代码，再根据邮件的内容查看代码：）
